name: macOS build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  boinc_ref: 82d0a3731c743884b6e7a25d68c6558eca691635  # client release 7.20.2


jobs:
  boinc-macIntel64:
    runs-on: macos-latest

    steps:
      - name: Cache BOINC libs
        id: cache-boinc-macIntel64
        uses: actions/cache@v3
        with:
          path: |
            boinc/mac_build/build/Deployment
            boinc/*.*
            boinc/api
            boinc/lib
          key: boinc-${{ runner.os }}-${{ env.boinc_ref }}-macIntel64

      - uses: maxim-lobanov/setup-xcode@v1
        if: steps.cache-boinc-macIntel64.outputs.cache-hit != 'true'
        with:
          xcode-version: '14.3.1'

      - name: Checkout boinc
        if: steps.cache-boinc-macIntel64.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          repository: 'BOINC/boinc'
          ref: ${{ env.boinc_ref }}
          path: 'boinc'

      - name: build boinc
        if: steps.cache-boinc-macIntel64.outputs.cache-hit != 'true'
        run: |
          cd ./boinc/mac_build/
          source BuildMacBOINC.sh -lib

  macIntel64:
    needs: boinc-macIntel64
    runs-on: macos-latest

    steps:
      - name: Use cached BOINC libs
        id: cache-boinc
        uses: actions/cache@v3
        with:
          path: |
            boinc/mac_build/build/Deployment
            boinc/*.*
            boinc/api
            boinc/lib
          key: boinc-${{ runner.os }}-${{ env.boinc_ref }}-macIntel64

      - name: Fail if boinc missing
        if: steps.cache-boinc.outputs.cache-hit != 'true'
        run: exit 1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - name: install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: install deps (brew)
        run: brew install gmp

      - name: remove dylib files (force static link)
        run: |
          rm -f /usr/local/opt/libomp/lib/libomp.dylib
          rm -f /usr/local/opt/gmp/lib/libgmp.dylib

      - name: Checkout genefer22
        uses: actions/checkout@v3
        with:
          path: 'prst'

      - name: make
        run: cd src/mac64 && make -j

      - name: make (boinc)
        run: make -f Makefile.boinc -j

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macIntel64_bins
          path: |
            src/mac64/prst
            src/mac64/prst_boinc